### ISSUE TITLE
Vercel deployment - Error: Logtail source token missing

### ISSUE THREAD

**Issue by yasmeen** [synchronicity-labs/translation-starter#36]
I'm seeing this error in the vercel deployment. Any idea how to fix this?

```
[13:03:04.906] Running build in Washington, D.C., USA (East) – iad1
[13:03:05.256] Cloning github.com/yasmeen/translation-starter-1 (Branch: main, Commit: 4a2208a)
[13:03:05.618] Previous build cache not available
[13:03:06.057] Cloning completed: 800.374ms
[13:03:06.446] Running "vercel build"
[13:03:09.026] Vercel CLI 33.2.0
[13:03:09.491] Installing dependencies...
[13:03:09.825] yarn install v1.22.17
[13:03:09.942] [1/4] Resolving packages...
[13:03:10.248] [2/4] Fetching packages...
[13:03:34.459] [3/4] Linking dependencies...
[13:03:34.468] warning " > @ianvs/prettier-plugin-sort-imports@3.7.2" has incorrect peer dependency "prettier@2.x".
[13:03:42.315] [4/4] Building fresh packages...
[13:03:43.201] Done in 33.38s.
[13:03:43.225] Detected Next.js version: 13.4.3
[13:03:43.267] Running "yarn run build"
[13:03:43.457] yarn run v1.22.17
[13:03:43.484] $ next build
[13:03:43.928] - warn You have enabled experimental feature (serverActions) in next.config.js.
[13:03:43.929] - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[13:03:43.929] 
[13:03:43.966] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[13:03:43.967] This information is used to shape Next.js' roadmap and prioritize features.
[13:03:43.967] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[13:03:43.968] https://nextjs.org/telemetry
[13:03:43.968] 
[13:03:44.061] - info Creating an optimized production build...
[13:04:21.416] - warn Compiled with warnings
[13:04:21.416] 
[13:04:21.416] ./node_modules/@ffmpeg/ffmpeg/dist/esm/worker.js
[13:04:21.417] Critical dependency: the request of a dependency is an expression
[13:04:21.417] 
[13:04:21.417] Import trace for requested module:
[13:04:21.417] ./node_modules/@ffmpeg/ffmpeg/dist/esm/worker.js
[13:04:21.417] ./node_modules/@ffmpeg/ffmpeg/dist/esm/classes.js
[13:04:21.417] ./node_modules/@ffmpeg/ffmpeg/dist/esm/index.js
[13:04:21.417] ./utils/load-ffmpeg.ts
[13:04:21.417] ./components/feature-playground/ui/MediaInput/MediaInput.tsx
[13:04:21.417] 
[13:04:21.417] ./node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
[13:04:21.417] Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
[13:04:21.417] 
[13:04:21.417] Import trace for requested module:
[13:04:21.417] ./node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
[13:04:21.417] ./node_modules/@emotion/react/dist/emotion-react.esm.js
[13:04:21.417] ./node_modules/@chakra-ui/system/dist/index.mjs
[13:04:21.417] ./node_modules/@chakra-ui/react/dist/index.mjs
[13:04:21.418] ./app/page.tsx
[13:04:21.418] 
[13:04:21.418] ./node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
[13:04:21.418] Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
[13:04:21.420] 
[13:04:21.421] Import trace for requested module:
[13:04:21.421] ./node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
[13:04:21.421] ./node_modules/@emotion/react/dist/emotion-react.esm.js
[13:04:21.421] ./node_modules/@chakra-ui/system/dist/index.mjs
[13:04:21.421] ./node_modules/@chakra-ui/react/dist/index.mjs
[13:04:21.421] ./app/page.tsx
[13:04:21.421] 
[13:04:21.421] ./node_modules/@emotion/react/dist/emotion-react.esm.js
[13:04:21.421] Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').
[13:04:21.421] 
[13:04:21.421] Import trace for requested module:
[13:04:21.422] ./node_modules/@emotion/react/dist/emotion-react.esm.js
[13:04:21.427] ./node_modules/@chakra-ui/system/dist/index.mjs
[13:04:21.427] ./node_modules/@chakra-ui/react/dist/index.mjs
[13:04:21.427] ./app/page.tsx
[13:04:21.427] 
[13:04:21.427] ./node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
[13:04:21.427] Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'React').
[13:04:21.427] 
[13:04:21.427] Import trace for requested module:
[13:04:21.429] ./node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
[13:04:21.429] ./node_modules/@emotion/react/dist/emotion-react.esm.js
[13:04:21.429] ./node_modules/@chakra-ui/system/dist/index.mjs
[13:04:21.429] ./node_modules/@chakra-ui/react/dist/index.mjs
[13:04:21.429] ./app/page.tsx
[13:04:21.429] 
[13:04:21.429] - info Linting and checking validity of types...
[13:04:24.076] - warn The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
[13:04:37.779] 
[13:04:37.779] ./app/api/create-checkout-session/route.ts
[13:04:37.780] 1:19  Warning: 'headers' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.780] 
[13:04:37.780] ./app/api/db/create-job/route.ts
[13:04:37.780] 20:11  Warning: 'jobId' is assigned a value but never used.  @typescript-eslint/no-unused-vars
[13:04:37.780] 
[13:04:37.780] ./app/api/lip-sync/webhook/route.ts
[13:04:37.780] 1:1  Warning: There should be at least one empty line between import groups  import/order
[13:04:37.780] 2:1  Warning: `@supabase/supabase-js` import should occur before import of `@/lib/SynchronicityLogger`  import/order
[13:04:37.780] 
[13:04:37.780] ./app/auth/callback/route.ts
[13:04:37.780] 7:15  Warning: 'Database' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.780] 
[13:04:37.780] ./app/page.tsx
[13:04:37.780] 16:34  Warning: 'user' is assigned a value but never used.  @typescript-eslint/no-unused-vars
[13:04:37.780] 
[13:04:37.780] ./app/subscription/page.tsx
[13:04:37.780] 9:3  Warning: 'getCreditBalance' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.780] 
[13:04:37.780] ./components/feature-home/ui/Intstructions/index.tsx
[13:04:37.780] 5:10  Warning: 'Box' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.780] 
[13:04:37.780] ./components/feature-playground/ui/JobGrid/JobGridItem/JobGridItem.tsx
[13:04:37.780] 3:14  Warning: 'useState' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.780] 
[13:04:37.780] ./components/feature-playground/ui/MediaInput/YoutubeInput.tsx
[13:04:37.780] 3:10  Warning: 'Button' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.780] 3:31  Warning: 'Tooltip' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.780] 6:10  Warning: 'checkIfValidYoutubeUrl' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.781] 
[13:04:37.781] ./components/feature-subscription/ui/SubscriptionDetails/CreditsDetails.tsx
[13:04:37.781] 4:3  Warning: 'Badge' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.781] 5:3  Warning: 'Box' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.781] 
[13:04:37.781] ./components/feature-subscription/ui/SubscriptionDetails/PlanDetails.tsx
[13:04:37.781] 3:28  Warning: 'Spinner' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.781] 
[13:04:37.781] ./components/feature-usage/ui/UsageTable/UsageTable.tsx
[13:04:37.781] 49:34  Warning: 'userId' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.781] 
[13:04:37.781] ./components/ui/Display/Pricing/Pricing.tsx
[13:04:37.781] 42:9  Warning: 'intervals' is assigned a value but never used.  @typescript-eslint/no-unused-vars
[13:04:37.781] 50:27  Warning: 'setBillingInterval' is assigned a value but never used.  @typescript-eslint/no-unused-vars
[13:04:37.781] 
[13:04:37.781] ./components/ui/Navbar/Navbar.tsx
[13:04:37.781] 5:10  Warning: 'FaDollarSign' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.781] 5:24  Warning: 'FaRegWindowMaximize' is defined but never used.  @typescript-eslint/no-unused-vars
[13:04:37.781] 
[13:04:37.781] info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[13:04:38.757] - info Collecting page data...
[13:04:39.319] Error: Logtail source token missing
[13:04:39.320]     at new Logtail (/vercel/path0/.next/server/chunks/4156.js:73:19)
[13:04:39.321]     at new default_1 (/vercel/path0/.next/server/chunks/4156.js:323:1)
[13:04:39.321]     at new Node (/vercel/path0/.next/server/chunks/4156.js:493:9)
[13:04:39.322]     at 12767 (/vercel/path0/.next/server/chunks/2767.js:28:17)
[13:04:39.323]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[13:04:39.323]     at 7684 (/vercel/path0/.next/server/app/api/clone-voice/route.js:246:27)
[13:04:39.323]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[13:04:39.323]     at __webpack_exec__ (/vercel/path0/.next/server/app/api/clone-voice/route.js:357:39)
[13:04:39.323]     at /vercel/path0/.next/server/app/api/clone-voice/route.js:358:106
[13:04:39.323]     at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:150:21)
[13:04:39.328] 
[13:04:39.328] > Build error occurred
[13:04:39.328] Error: Failed to collect page data for /api/clone-voice
[13:04:39.328]     at /vercel/path0/node_modules/next/dist/build/utils.js:1152:15
[13:04:39.328]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[13:04:39.329]   type: 'Error'
[13:04:39.329] }
[13:04:39.448] error Command failed with exit code 1.
[13:04:39.448] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[13:04:39.466] Error: Command "yarn run build" exited with 1
[13:04:39.816] 
```

**Comment by jashanpratapsingh** [comment]
Hey even I am unable to build from a few hours. Can someone solve this issue? Also is there a way to clone the repo directly into the local system and then run it?

**Comment by roberto-ceraolo** [comment]
It's not mentioned explicitly in the readme, but you should add the Logtail / Better Stack integration ([here](https://betterstack.com/logs) their website).

Also, you should add an environment variable INNGEST_CLIENT_ID containing the name of your inngest project

**Comment by utkarshwealthy** [comment]
Just wanted to add that same issue for me as well.
Even I'm not being able to run this on local, it says:- Error fetching Jobs

**Comment by darbybailey** [comment]
I integrated betterstack with vercel and it cleaned up that error for me (there are still react errors and inngest errors I'm working on next)

**Comment by chenjiachen32** [comment]
> I integrated betterstack with vercel and it cleaned up that error for me (there are still react errors and inngest errors I'm working on next)

Hello, have you solved the reat errors? I also meet this errors. But it completed the deployment even with these errors. And I find that after I drag my video to the product site, it is always showing "pending" status. I don't know if it is related to the react errors.
